repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: debug-statements
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language_version: python3
        files: ^src/
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
        args:
          - --application-directories=.:src
          - --py36-plus
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - --py311-plus
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        files: ^src/
        args:
          - --config-file
          - mypy.ini
          - --install-types
          - --non-interactive
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        types:
          - python
        args:
          - --add-import
          - from __future__ import annotations
        exclude: "(?x)(\n   ^(install|get)-poetry.py$\n    | ^src/poetry/__init__.py$\n)\n"
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args:
          - src/
          - --target-version=py311
          - --target-version=py310
        exclude: ^.cache/
  - repo: local
    hooks:
      - id: export-requirements
        name: Export requirements.txt
        language: system
        pass_filenames: false
        entry: poetry export -f requirements.txt --output requirements.txt
        files: ^(pyproject.toml|poetry.lock)$
  - repo: local
    hooks:
      - id: local-integration-tests
        name: local-integration-tests
        language: system
        pass_filenames: false
        entry: ./entrypoint.sh PreCommitTest
        always_run: true
