version: "3"

networks:
  inner_net:
    driver: bridge

services:

  api:
    container_name: "API_${CONTOUR}"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "9999:9999"
    networks:
      - inner_net
    entrypoint: "${API_ENTRYPOINT}"

  redis:
    container_name: "REDIS_${CONTOUR}"
    image: redis:latest
    env_file:
      - .env
    depends_on:
      - api
    networks:
      - inner_net
